services:
  - type: web
    name: face-app
    env: docker
    repo: https://github.com/Ye-Thihaa/la-pj.git # Replace with your GitHub repo URL
    region: oregon # or singapore for closer to your location
    plan: starter # Free tier
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: face-app-disk
      mountPath: /app/static
      sizeGB: 1